### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by r3mus99** [bohdanbirdie/mobx-react-lite-example1#1]
doesnt work with mobx 6+ and mobx-react-lite 3+

**Comment by bohdanbirdie** [comment]
@r3mus99 mobx-react-lite was merged into mobx itself, but except that all guides are still relevant ;)

**Comment by r3mus99** [comment]
I don't know about that. When I updated mobx / mobx-lite to the latest, observer stopped working. but

`constructor() {
    makeAutoObservable(this);
}`

in store class solved problem

**Comment by bohdanbirdie** [comment]
@r3mus99 ah, yes, you're correct :)
